# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportcenterApp', '0004_auto_20180718_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('creation_date', models.DateTimeField()),
                ('booking_id', models.CharField(max_length=255)),
                ('time_period', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('sportcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Sportcenters')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
