# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0006_auto_20180723_1411'),
        ('booking', '0003_booking_booking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='terrainAvailibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notAvailableFrom', models.DateTimeField(blank=True)),
                ('notAvailableTill', models.DateTimeField(blank=True)),
                ('opening', models.DateTimeField(blank=True)),
                ('closing', models.DateTimeField(blank=True)),
                ('sportcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Sportcenters')),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Terrain')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='day_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('ce013029-001c-40b7-a28f-b68a20bb1cf9'), max_length=254),
        ),
    ]
