# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20180723_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrainavailibility',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='terrainavailibility',
            name='opening',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('6ffdd9ee-c7dd-4aa2-8fc8-329e5068af4d'), max_length=254),
        ),
        migrations.AlterField(
            model_name='terrainavailibility',
            name='notAvailableFrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='terrainavailibility',
            name='notAvailableTill',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
