# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authorize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportcenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('TelephoneNumber', models.CharField(max_length=12)),
                ('ImagePath', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('Description', models.TextField(max_length=140)),
                ('Partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authorize.Partners')),
            ],
            options={
                'verbose_name_plural': 'Sportcenters',
            },
        ),
    ]
