# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sportcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Sportcenters')),
            ],
            options={
                'verbose_name_plural': 'Photo',
            },
        ),
    ]
