# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerrainType', models.CharField(max_length=255)),
                ('Capacity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('TotalTerrains', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sportcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportcenterApp.Sportcenters')),
            ],
            options={
                'verbose_name_plural': 'Terrain',
            },
        ),
    ]
