# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-18 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0003_terrain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportcenters',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='updated_at',
        ),
    ]
