# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0004_auto_20180718_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='TotalTerrains',
        ),
    ]
