# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0005_remove_terrain_totalterrains'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terrain',
            old_name='Capacity',
            new_name='maximumCapacity',
        ),
        migrations.AddField(
            model_name='terrain',
            name='minimumCapacity',
            field=models.IntegerField(default=0),
        ),
    ]
