# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportcenterApp', '0006_auto_20180723_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='closing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terrain',
            name='opening',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
